/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.62
 * Generated at: 2022-05-01 08:29:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class NewFile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

	

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<!-- This site was created in Webflow. http://www.webflow.com -->\r\n");
      out.write("<!-- Last Published: Sun May 01 2022 08:25:41 GMT+0000 (Coordinated Universal Time) -->\r\n");
      out.write("<html data-wf-domain=\"6832s-superb-site.webflow.io\"\r\n");
      out.write("	data-wf-page=\"626e3140a5f90a4daf0b2383\"\r\n");
      out.write("	data-wf-site=\"626e3140a5f90ae6560b2381\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\" />\r\n");
      out.write("<title>6832&#x27;s Superb Site</title>\r\n");
      out.write("<meta content=\"width=device-width, initial-scale=1\" name=\"viewport\" />\r\n");
      out.write("<meta content=\"Webflow\" name=\"generator\" />\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://uploads-ssl.webflow.com/626e3140a5f90ae6560b2381/css/6832s-superb-site.webflow.f34cf2b21.css\"\r\n");
      out.write("	rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<!--[if lt IE 9]><script src=\"https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js\" type=\"text/javascript\"></script><![endif]-->\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	!function(o, c) {\r\n");
      out.write("		var n = c.documentElement, t = \" w-mod-\";\r\n");
      out.write("		n.className += t + \"js\", (\"ontouchstart\" in o || o.DocumentTouch\r\n");
      out.write("				&& c instanceof DocumentTouch)\r\n");
      out.write("				&& (n.className += t + \"touch\")\r\n");
      out.write("	}(window, document);\r\n");
      out.write("</script>\r\n");
      out.write("<link href=\"https://uploads-ssl.webflow.com/img/favicon.ico\"\r\n");
      out.write("	rel=\"shortcut icon\" type=\"image/x-icon\" />\r\n");
      out.write("<link href=\"https://uploads-ssl.webflow.com/img/webclip.png\"\r\n");
      out.write("	rel=\"apple-touch-icon\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"body\">\r\n");
      out.write("	<header class=\"title wf-section\"></header>\r\n");
      out.write("	<header class=\"headbar wf-section\">\r\n");
      out.write("		<div class=\"w-layout-grid grid-3\">\r\n");
      out.write("			<div></div>\r\n");
      out.write("			<div>Home</div>\r\n");
      out.write("			<div>About</div>\r\n");
      out.write("			<div>Best</div>\r\n");
      out.write("			<div>Genre A</div>\r\n");
      out.write("			<div>Genre B</div>\r\n");
      out.write("			<div>MyPage</div>\r\n");
      out.write("			<div></div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</header>\r\n");
      out.write("	<div class=\"w-row\">\r\n");
      out.write("		<div class=\"column-13 w-col w-col-2\">\r\n");
      out.write("			<ul role=\"list\" class=\"list w-list-unstyled\">\r\n");
      out.write("				<li class=\"list-item\">Menu 1</li>\r\n");
      out.write("				<li>Menu 2</li>\r\n");
      out.write("				<li>Menu 3</li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"column-14 w-col w-col-8\">\r\n");
      out.write("			<h1>Heading</h1>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"column-15 w-col w-col-2\"></div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<footer id=\"footer\" class=\"footer wf-section\">\r\n");
      out.write("		<div class=\"w-container\">\r\n");
      out.write("			<div class=\"footer-flex-container\">\r\n");
      out.write("				<a href=\"#\" class=\"footer-logo-link\"><img\r\n");
      out.write("					src=\"https://uploads-ssl.webflow.com/5db1c76aadcfe25e881680fa/5db86dc421496616bf357c25_placeholder.svg\"\r\n");
      out.write("					alt=\"\" class=\"footer-image\" /></a>\r\n");
      out.write("				<div>\r\n");
      out.write("					<h2 class=\"footer-heading\">Heading Label</h2>\r\n");
      out.write("					<ul role=\"list\" class=\"w-list-unstyled\">\r\n");
      out.write("						<li><a href=\"#\" class=\"footer-link\">Text Link</a></li>\r\n");
      out.write("						<li><a href=\"#\" class=\"footer-link\">Text Link</a></li>\r\n");
      out.write("						<li><a href=\"#\" class=\"footer-link\">Text Link</a></li>\r\n");
      out.write("						<li><a href=\"#\" class=\"footer-link\">Text Link</a></li>\r\n");
      out.write("						<li><a href=\"#\" class=\"footer-link\">Text Link</a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div>\r\n");
      out.write("					<h2 class=\"footer-heading\">Heading Label</h2>\r\n");
      out.write("					<ul role=\"list\" class=\"w-list-unstyled\">\r\n");
      out.write("						<li><a href=\"#\" class=\"footer-link\">Text Link</a></li>\r\n");
      out.write("						<li><a href=\"#\" class=\"footer-link\">Text Link</a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div>\r\n");
      out.write("					<h2 class=\"footer-heading\">Heading Label</h2>\r\n");
      out.write("					<ul role=\"list\" class=\"w-list-unstyled\">\r\n");
      out.write("						<li><a href=\"#\" class=\"footer-link\">Text Link</a></li>\r\n");
      out.write("						<li><a href=\"#\" class=\"footer-link\">Text Link</a></li>\r\n");
      out.write("						<li><a href=\"#\" class=\"footer-link\">Text Link</a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div>Copyright 2020 My Company. All rights reserved.</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</footer>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"https://d3e54v103j8qbb.cloudfront.net/js/jquery-3.5.1.min.dc5e7f18c8.js?site=626e3140a5f90ae6560b2381\"\r\n");
      out.write("		type=\"text/javascript\"\r\n");
      out.write("		integrity=\"sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=\"\r\n");
      out.write("		crossorigin=\"anonymous\"></script>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"https://uploads-ssl.webflow.com/626e3140a5f90ae6560b2381/js/webflow.7f033afae.js\"\r\n");
      out.write("		type=\"text/javascript\"></script>\r\n");
      out.write("	<!--[if lte IE 9]><script src=\"//cdnjs.cloudflare.com/ajax/libs/placeholders/3.0.2/placeholders.min.js\"></script><![endif]-->\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
